#pragma once

// This file is automatically generated, modify at your peril

#define usb_spi_MODE_0 1

#define usb_spi_MODE_1 2

#define usb_spi_MODE_2 4

#define usb_spi_MODE_3 8

#define usb_spi_ANY_MODE 15

#define usb_spi_MSB_FIRST 16

#define usb_spi_LSB_FIRST 32

#define usb_spi_INTERRUPT 64

#define usb_spi_RESET 128

/**
 * Used as the request field of IN control transfers
 */
enum usb_spi_ControlIn {
  usb_spi_ControlIn_HwInfo,
  usb_spi_ControlIn_GetEvent,
  /**
   * Slave ID is sent in the value field
   */
  usb_spi_ControlIn_LinuxSlaveInfo,
};
typedef uint8_t usb_spi_ControlIn;

/**
 * Used as the request field of OUT control transfers
 */
enum usb_spi_ControlOut {
  /**
   * Slave ID is in the value field
   */
  usb_spi_ControlOut_AssertReset,
  /**
   * Slave ID is in the value field
   */
  usb_spi_ControlOut_DeassertReset,
};
typedef uint8_t usb_spi_ControlOut;

/**
 * USB convention of the directions used in this transfer
 *
 * USB is used because the protocol could be used for attaching SPI controllers
 * or peripherals, but the logic around headers going in OUT transfer wouldn't
 * change based on the SPI direction.
 */
enum usb_spi_Direction {
  usb_spi_Direction_None,
  usb_spi_Direction_OutOnly,
  usb_spi_Direction_InOnly,
  usb_spi_Direction_Both,
};
typedef uint8_t usb_spi_Direction;

enum usb_spi_EventType {
  usb_spi_EventType_NoEvent,
  usb_spi_EventType_Interrupt,
  usb_spi_EventType_Error,
};
typedef uint8_t usb_spi_EventType;

/**
 * Functions as something like a communications protocol version
 */
enum usb_spi_HardwareType {
  usb_spi_HardwareType_SpiMaster,
};
typedef uint8_t usb_spi_HardwareType;

/**
 * Returned by SPI masters for REQUEST_IN_LINUX_SLAVE_INFO
 */
typedef struct usb_spi_ConnectedSlaveInfoLinux {
  /**
   * NULL-terminated, 32 comes from Linux's SPI_NAME_SIZE TODO use const
   */
  uint8_t modalias[32];
  uint32_t max_speed_hz;
  uint8_t capabilities;
} usb_spi_ConnectedSlaveInfoLinux;

typedef struct usb_spi_Event {
  /**
   * Some events contain more information, it goes here
   *
   * Interrupt: which device index is interrupting
   * Error: enum value of the specific error
   */
  uint16_t data;
  usb_spi_EventType event_type;
} usb_spi_Event;

typedef struct usb_spi_MasterInfo {
  /**
   * Encode as SpiMaster
   */
  usb_spi_HardwareType hardware;
  uint32_t max_speed_hz;
  uint16_t slave_count;
  /**
   * Bytes that can be read in by the SPI before USB IN transfers start
   */
  uint16_t in_buf_size;
} usb_spi_MasterInfo;

/**
 * Sent through the bulk OUT endpoint, possibly before any OUT data
 */
typedef struct usb_spi_TransferHeader {
  uint16_t bytes;
  /**
   * Index of the slave device the transfer is intended for
   */
  uint16_t index;
  uint32_t speed_hz;
  usb_spi_Direction direction;
  uint8_t mode;
} usb_spi_TransferHeader;
