// This file is automatically generated, modify at your peril

/**
 * Used as the request field of IN control transfers
 */
enum usb_spi_ControlIn {
  REQUEST_IN_HW_INFO,
  REQUEST_IN_GET_EVENT,
  /**
   * Slave ID is sent in the value field
   */
  REQUEST_IN_LINUX_SLAVE_INFO,
};
typedef uint8_t usb_spi_ControlIn;

/**
 * Used as the request field of OUT control transfers
 */
enum usb_spi_ControlOut {
  SetSlave,
};
typedef uint8_t usb_spi_ControlOut;

/**
 * USB convention of the directions used in this transfer
 *
 * USB is used because the protocol could be used for attaching SPI controllers
 * or peripherals, but the logic around headers going in OUT transfer wouldn't
 * change based on the SPI direction.
 */
enum usb_spi_Direction {
  /**
   * Only used internally in the firmware, not for over-the-wire protocol
   */
  None,
  OutOnly,
  InOnly,
  Both,
};
typedef uint8_t usb_spi_Direction;

enum usb_spi_EventType {
  NONE,
};
typedef uint8_t usb_spi_EventType;

/**
 * Functions as something like a communications protocol version
 */
enum usb_spi_HardwareType {
  SpiMaster,
};
typedef uint8_t usb_spi_HardwareType;

typedef struct usb_spi_MasterInfo {
  /**
   * Encode as SpiMaster
   */
  usb_spi_HardwareType hardware;
  uint16_t slave_count;
  /**
   * Bytes that can be read in by the SPI before USB IN transfers start
   */
  uint16_t in_buf_size;
} usb_spi_MasterInfo;

/**
 * Returned by SPI masters for REQUEST_IN_LINUX_SLAVE_INFO
 */
typedef struct usb_spi_ConnectedSlaveInfoLinux {
  uint8_t has_interrupt;
  /**
   * NULL-terminated, 32 comes from Linux's SPI_NAME_SIZE TODO use const
   */
  uint8_t modalias[32];
} usb_spi_ConnectedSlaveInfoLinux;

typedef struct usb_spi_Event {
  usb_spi_EventType event;
} usb_spi_Event;

typedef struct usb_spi_SetSlave {
  uint16_t slave_id;
} usb_spi_SetSlave;

/**
 * Sent through the bulk OUT endpoint, possibly before any OUT data
 */
typedef struct usb_spi_TransferHeader {
  uint16_t bytes;
  usb_spi_Direction direction;
} usb_spi_TransferHeader;
